### ISSUE TITLE
State change when call is paused by remote

### ISSUE THREAD

**Issue by jelenadj** [BelledonneCommunications/linphone-iphone#206] opened 2017-03-14 11:05 UTC
After establishing a call, when `linphone_core_pause_call` is triggered, call is paused and another side is hearing hold music, all good. However, I didn't receive any state change in `static void linphone_iphone_call_state(LinphoneCore *lc, LinphoneCall *call, LinphoneCallState state, const char *message) ` in my app on another side. What else is required to be able to get call state change to `LinphoneCallPausedByRemote` when call is paused by remote?

**Comment by ReisBenjamin** [comment] 2017-03-14 12:25
You need to implement a callback onCallStateChanged on the receiver side.
On the sender side calling linphone_core_pause_call i enough

**Comment by jelenadj** [comment] 2017-03-14 12:35
I have implemented this callback `- (void)onCall:(LinphoneCall *)call StateChanged:(LinphoneCallState)state withMessage:(const char *)message`, and I am receiving other call state changes, like initialization, ringing, connecting, pausing, paused, etc. However, from some reason I am not receiving `LinphoneCallPausedByRemote` on remote side..
So, one side is changed properly to Paused state, but another side just starts with receiving hold music, but there is no call state change.
When I try the same with latest Linphone app, I am getting this call state, but not in my project where I am getting other state changes but not for PausedByRemote. I am using lib version from 3.15 release. Is there some known change in meantime related with this feature? Should I try with 3.16?

**Comment by ReisBenjamin** [comment] 2017-03-14 12:36
Yes you should try with our latest release SDK (3.16.2)

**Comment by jelenadj** [comment] 2017-03-14 13:38
Somehow I am still having the same issue with 3.16.2, call state change is not detected on remote side. Only side that puts call on hold is getting call state changes. Can you think about anything (configuration related) that could affect not changing into PausedByRemote state after calling linphone_core_pause_call?
Also, not so important, but: is there a way to disable 3-beep indicator sound on hold-initiator side?
Thanks in advance.

**Comment by ReisBenjamin** [comment] 2017-03-21 16:34
I don't hear any beep when i set a call in pause.
I don't understant what you mean.

**Comment by jelenadj** [comment] 2017-03-22 14:29
I have installed Linhpone app from the AppStore on iPhone (iOS 10) and iPad (iOS 9). When I establish a call between them, and tap on pause button in Calling interface on iPhone side, call is put on hold, iPad is hearing hold music, but I can also hear repeating beeps in equal intervals on iPhone headset. Is it maybe intentionally, in case that call is paused manually, to warn user on initiator side about paused call?
When I receive another call, and put this one on hold, there is no beeps. Only if I pause it manually using Linphone call interface, it plays some repeating beep.

**Comment by jelenadj** [comment] 2017-03-27 19:05
By headset I mean my standard (iPhone 6S) earpiece. In any case, it's not blocking me on any way, just curios why it behaves differently when user manually put call on hold, then when call is put on hold by receiving another call :). Thanks.

**Comment by ReisBenjamin** [comment] 2017-03-28 13:11
Okay then i'll close the issue.
Do not hesitate to repoen one if you have more questions.

**Closed by ReisBenjamin** 2017-03-28 13:11 UTC

**Comment by TheNazzi89** [comment] 2017-05-08 19:48
Hi Jelendj
I have the same issue. You said that you've realized the reason. Can you help me, please?

**Comment by jelenadj** [comment] 2017-05-08 21:13
@TheNazzi89 it depends of how your calls are handled on the server side. If your 1-1 call is established as a bridge (conference call), in this case you actually have 2 different calls in the same "room", and pausing call on your side will not pause the call of another person, because those two are completely separated calls. That was my case.

**Comment by TheNazzi89** [comment] 2017-05-08 22:04
@jelenadj First of all, thanks for your reply. So, according to you, that's a server-side problem. But, I have two different versions of the app. One that I stopped editing 8 months ago a new one that I'm working on. If I call from the Old version to the New version, it pauses on both side. From the New version to the New version it doesn't work. Furthermore, if I call from the New version to an Android Linphone, it work. In all of these cases, the server is the same. Could I know what did you do on server and/or on client to solve this issue?

P.S. The new version works with Voip Push Notifications.

**Comment by jelenadj** [comment] 2017-05-08 22:25
@TheNazzi89 You said "If I call from the Old version to the New version, it pauses on both side", does it mean that you are putting call on hold from the old version, i.e. the old version receives another call, and puts the current one (with the new version) on hold? Or is call paused on both side no matter which side triggered linphone_core_pause_call? Do you have CallKit support on the new version? VOIP push shouldn't make any issue here...

**Comment by TheNazzi89** [comment] 2017-05-08 22:29
@jelenadj 
- call is paused on both side no matter which side triggered linphone_core_pause_call
- I have CallKit support on the new version.

**Comment by jelenadj** [comment] 2017-05-08 22:59
@TheNazzi89 Since it works for you between New version and Android Linphone, does it also works between New version and iOS Linphone app? Sorry, my arch is obviously different, since it didn't work even in those cases that works for you, so maybe Benjamin can provide more help here... Do you have a problem with pausing calls only if both apps are your own apps on iOS, or is it OS related so you can't get a call state change into "paused by remote" even if you establish a call between your new version and latest Linphone app for iOS?

**Comment by TheNazzi89** [comment] 2017-05-08 23:28
Summary:
- Old Version to New Version: working
- New Version to Old Version: working
- Old Version to Old Version: working(so, definitely, it's not a server-side issue)
- New Version to New Version: NOT WORKING

In addition, from the New to New, during a call on my side the Pause button, the Video button and the Options button are enabled, but on the remote side those buttons are disabled. And I noticed that if I remove **_linphone_core_sound_resources_locked(LC)_**(returns a boolean) from _updateButtomBar_ and from _onUpdate_ functions of **CallView.m**, of **UIPauseButton.m** and of **UIVideoButton.m**, they are always enabled on remote side. But if I triggered the Pause Button, I'm not able to go back to the call(I mean can't talk again to remote side). So, I think the problem is in this function. Somehow the sound resources are blocked.

Let me know if you guys can help me solving this issue, please.

**Comment by TheNazzi89** [comment] 2017-05-16 18:22
PROBLEM SOLVED

I had ice_preference enabled without a stun server. That was the reason.
