### ISSUE TITLE
Not able to connect to my SIP server.

### ISSUE THREAD

**Issue by kannanprasad87** [BelledonneCommunications/linphone-iphone#39] opened 2016-02-17 13:49 UTC
I  am able to build the code and The test cases in KIF are also getting passed.
But on connecting to my SIP server, I am not able to register it. I am able to register with my Linphone account also.

I am trying from iPhone with 3G data. Is this server configuration error or am I missing anything?

**Below given is the logs**

>2016-02-17 18:49:37:411 ortp-message-channel [0xe4c000]: message sent to [UDP://52.36.69.120:5060], size: [759] bytes
REGISTER sip:52.36.37.80 SIP/2.0
Via: SIP/2.0/UDP 100.113.221.221:5060;branch=z9hG4bK.vMrPQVmaU;rport
From: <sip:kannan@52.36.37.80>;tag=61dsGibAv
To: sip:kannan@52.36.37.80
CSeq: 24 REGISTER
Call-ID: p9XgJfzbja
Max-Forwards: 70
Supported: outbound
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: <sip:kannan@100.113.221.221;app-id=com.ust.devicedebug.dev;pn-type=apple;pn-tok=92125AA604B8A9EE093A547F3D06BD0135BCF06F1189BD664E93F96C6720CF92;pn-msg-str=IM_MSG;pn-call-str=IC_MSG;pn-call-snd=notes_of_the_optimistic.caf;pn-msg-snd=msg.caf>;+sip.instance="<urn:uuid:fa4cdf64-3a96-41cd-b5fe-431093c965e0>"
Expires: 3600
User-Agent: Linphone_iPhone4,1_iOS7.1.2/3.11.8-13-gb095cd2 (belle-sip/1.4.2)
2016-02-17 18:49:37:909 ortp-message-A timeout related to this channel occured and no message received during last 60 seconds. This channel is suspect, moving to error state
2016-02-17 18:49:37:910 ortp-message-channel 0xe4c000: state ERROR
2016-02-17 18:49:37:910 ortp-warning-Transaction [0x17021a40] reporting timeout, reporting to channel.
2016-02-17 18:49:37:929 ortp-message-transaction [0x17021a40] channel state changed to [ERROR]
2016-02-17 18:49:37:930 ortp-message-Refresher: scheduling next timer in 60000 ms
2016-02-17 18:49:37:930 ortp-message-Register refresher  [503] reason [io error] for proxy [<sip:52.36.69.120;transport=udp>]
2016-02-17 18:49:37:930 ortp-message-Refresher: scheduling next timer in 2000 ms
2016-02-17 18:49:37:930 ortp-message-Register refresher  [408] reason [timeout] for proxy [<sip:52.36.69.120;transport=udp>]
2016-02-17 18:49:37:930 ortp-message-Changing [client] [REGISTER] transaction [0x17021a40], from state [TRYING] to [TERMINATED]
2016-02-17 18:49:37:930 ortp-message-Client internal REGISTER transaction [0x17021a40] terminated
2016-02-17 18:49:39:950 ortp-message-Channel [0xe4c000] destroyed
2016-02-17 18:49:39:950 ortp-message-Transaction [0x17021a40] deleted
2016-02-17 18:49:39:951 ortp-message-belle_sip_client_transaction_send_request(): waiting channel to be ready
2016-02-17 18:49:39:951 ortp-message-Background task belle-sip send channel started. Unknown remaining time since application is not fully in background.
2016-02-17 18:49:39:952 ortp-message-channel [0xe4c000]: starting send background task with id=[7].
2016-02-17 18:49:39:952 ortp-message-channel [0xe4c000]: starting resolution of 52.36.69.120
2016-02-17 18:49:39:952 ortp-message-channel 0xe4c000: state RES_IN_PROGRESS
2016-02-17 18:49:39:952 ortp-message-transaction [0x170299a0] channel state changed to [RES_IN_PROGRESS]
2016-02-17 18:49:39:952 ortp-message-channel 0xe4c000: state RES_DONE
2016-02-17 18:49:39:952 ortp-message-transaction [0x170299a0] channel state changed to [RES_DONE]
2016-02-17 18:49:39:952 ortp-message-channel 0xe4c000: state CONNECTING
2016-02-17 18:49:39:952 ortp-message-transaction [0x170299a0] channel state changed to [CONNECTING]
2016-02-17 18:49:39:953 ortp-message-Trying to connect to [UDP://52.36.69.120:5060]
2016-02-17 18:49:39:953 ortp-message-belle_sip_get_src_addr_for(): af_inet6=0
2016-02-17 18:49:39:953 ortp-message-Channel has local address 100.113.221.221:5060
2016-02-17 18:49:39:954 ortp-message-channel 0xe4c000: state READY
2016-02-17 18:49:39:954 ortp-message-transaction [0x170299a0] channel state changed to [READY]

**Comment by bagage** [comment] 2016-02-18 08:20
You should try with linphone desktop or linphone android or any other SIP client to check if your SIP account is working properly first. I am closing this now since this is not strictly speaking a linphone iOS bug, please use the users mailing list if extra help is required.

**Closed by bagage** 2016-02-18 08:20 UTC

**Comment by kannanprasad87** [comment] 2016-02-18 12:59
I have tried with different applications in Android and iOS and I could see
the account is working fine. Also the same code is working fine in
simulator but not working on real device.

Thanks & Regards
Kannan Prasad

**Comment by bagage** [comment] 2016-02-18 13:16
Then check your phone network; ideally check with another iOS device. If you are using the same network than simulator (eg Wifi), it should work identically.

**Comment by kannanprasad87** [comment] 2016-02-22 07:11
I am using the same network for both iOS device and simulator, Only iOs
device is throwing IO Error.

*Thanks & Regards*

*Kannan Prasad*

**Comment by kannanprasad87** [comment] 2016-02-22 17:03
I am really stuck over this point, Always getting the I/O error when trying
on the real device.

*Thanks & Regards*

*Kannan Prasad*

**Comment by bagage** [comment] 2016-02-23 09:16
I dont see any obvious reason here, but I really suggest you to test another network and another device to check what is the root cause (it may be Linphone, but also network or device).

**Comment by kannanprasad87** [comment] 2016-02-25 13:38
I am facing this issue in master branch. Which is the stable code branch? I
have tried in appstore branch but I am getting a white screen only in the
application

Thanks & Regards
Kannan Prasad

**Comment by kannanprasad87** [comment] 2016-02-25 13:40
Also one more thing I noted here is that I am able to connect to my sever
with same device using the app in the  store. Can you please confirm
whether it is a code issue or server issue. And also let me know what this
error exactly means ?

Thanks & Regards
Kannan Prasad

**Comment by bagage** [comment] 2016-02-25 13:51
Which version? 3.12 or 3.11? There is a communications error with your server (IO error) but I dont know what is wrong: maybe belle-sip, maybe iOS, maybe your server (check its logs), maybe something else...

**Comment by namdroid** [comment] 2017-06-28 16:42
We have the same issue. The client can register to the server, but some time we get "io error" again.

**Comment by namdroid** [comment] 2017-06-28 16:42
in Android client too

**Comment by namdroid** [comment] 2017-06-28 16:43
We use TCP.   "Register refresher [503] reason [io error] for proxy"

**Comment by anantsaraswat** [comment] 2018-10-10 14:08
Any update on this? Thanks in advance

**Comment by krishnastvSMSC** [comment] 2019-05-03 08:00
Am also facing same issue, any update

**Comment by piyush-ebizz** [comment] 2020-11-04 10:49
Hell @alll any update for this?
please let me know.
thanks

**Comment by piyush-ebizz** [comment] 2020-11-04 10:53
> I have tried with different applications in Android and iOS and I could see
> the account is working fine. Also the same code is working fine in
> simulator but not working on real device.
> 
> Thanks & Regards
> Kannan Prasad
> On Feb 18, 2016 13:50, "Gautier Pelloux-Prayer" [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > Closed #39
> > #39.
> > —
> > Reply to this email directly or view it on GitHub
> > [#39 (comment)](https://github.com/BelledonneCommunications/linphone-iphone/issues/39#event-554733342)
> > .

Have you found any solution? then please help me with this.

**Comment by chan1600** [comment] 2021-01-07 05:39
have the same issue

**Comment by bnsy** [comment] 2022-07-20 08:40
I am also facing the same issue 

Register refresher [503] reason [io error] for proxy [<sip:"";transport=tcp>]

Any help would be appreciated
