### ISSUE TITLE
Contacts are not being displayed

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#73] opened 2016-05-31 07:19 UTC
I am not able to see any contacts in contact list in this version 3.13. If I add a new contact, it also doesn't display in list. 
Although, in earlier version 3.12, it is working fine.

I am using Xcode 7.3.1 and Simulator iOS 9.3.

**Comment by bagage** [comment] 2016-05-31 07:21
Yes, contacts are broken on master - I am working on it.

**Comment by nitesh-borad** [comment] 2016-05-31 07:24
I also found two other issues. Should I comment out it here or create separate issues?

**Comment by bagage** [comment] 2016-05-31 07:25
Please create separate issues, I'll close them if irrelevant/duplicate of existing ones. Thanks!

**Comment by bagage** [comment] 2016-05-31 12:35
Fixed in 9feeeee

**Closed by bagage** 2016-05-31 12:35 UTC
