### ISSUE TITLE
Error building linphone SDK

### ISSUE THREAD

**Issue by daniel-legler** [BelledonneCommunications/linphone-iphone#399] opened 2018-03-08 18:33 UTC
I received the following error when trying to build the sdk:

> CMake Error at CMakeLists.txt:56 (find_package):
  By not providing "FindBCTOOLBOX.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "BCTOOLBOX", but CMake did not find one.
  Could not find a package configuration file provided by "BCTOOLBOX" with
  any of the following names:
    BCTOOLBOXConfig.cmake
    bctoolbox-config.cmake
  Add the installation prefix of "BCTOOLBOX" to CMAKE_PREFIX_PATH or set
  "BCTOOLBOX_DIR" to a directory containing one of the above files.  If
  "BCTOOLBOX" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!
See also "/Users/dlegler/dev/linphone-iphone/WORK/ios-x86_64/Build/msamr/CMakeFiles/CMakeOutput.log".
make[3]: *** [/Users/dlegler/dev/linphone-iphone/WORK/ios-x86_64/Stamp/EP_msamr/EP_msamr-configure] Error 1
make[2]: *** [CMakeFiles/EP_msamr.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [x86_64-build] Error 2

I ran the following commands for cloning the repo from the current master branch and building the SDK:
```
git clone https://github.com/BelledonneCommunications/linphone-iphone.git
git submodule update --init --recursive
./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_X264=ON -DENABLE_SILK=ON -DENABLE_AMRWB=ON && make
```
The cmake output log is here: [CMakeOutput.log](https://github.com/BelledonneCommunications/linphone-iphone/files/1794320/CMakeOutput.log)

Environment: 

> macOS High Sierra 10.13.3
Xcode 9.2 
iOS 11.2 SDK
C compiler is AppleClang 9.0.0.9000039

Has anyone ever seen this error and is there anything I can do to resolve it? Any help is appreciated.

**Comment by daniel-legler** [comment] 2018-03-09 21:10
I think there is a problem with one of your makefiles. I was able to workaround this issue by adding a prefix to the `./prepare.py` command:
```
BCTOOLBOX_DIR=/Users/dlegler/dev/linphone-iphone/WORK/ios-x86_64/Build/bctoolbox ./prepare.py ...
```

**Comment by ReisBenjamin** [comment] 2018-03-12 09:30
Hello,

Thanks for the report, we do not reproduce the issue.
We'll look into it.
I'll close the issue since you find a solution

Regards

**Closed by ReisBenjamin** 2018-03-12 09:30 UTC

**Comment by daniel-legler** [comment] 2018-03-12 21:11
@ReisBenjamin This is a case sensitivity issue. The actual file it's looking for is `BCTOOLBOXConfig.cmake` or ` bctoolbox-config.cmake`, but the file that is created is `BcToolboxConfig.cmake`. My system is case-sensitive, that's why I have this issue. If you could update your scripts to produce the cmake file with the correct casing, that would fix this problem.
