### ISSUE TITLE
CallKit shows terminated call

### ISSUE THREAD

**Issue by alqa-dash** [BelledonneCommunications/linphone-iphone#200] opened 2017-03-06 14:04 UTC
Hello,

I'm using Linphone of version 3.10.2-549 and recently something strange has been started happening: when one part (e.g. iPhone) begins call to another device (iPad in my case) and pressed hangup button afterwards, sip-call successfully terminates (it is clear from asterisk and from Liphone logs) but when I try to lock iPhone's screen - I got CallKit view with call (which was already terminated) shown as put on hold. I compared source code with backup copy (ProviderDelegate, LinphoneAppDelegate and LInphoneManager) and did not find any suspicious changes which could cause the problem. Could anybody tell me how linphone_core_terminate_call let CallKit know that call has been terminated? Actually I'm stuck with this for now.

Thanks in advance.

**Comment by ReisBenjamin** [comment] 2017-03-06 17:21
This issue has been fixed in commit d20aa3382ccccca3e7ce5e86111add0de31483b8
Please update your sources and tell me if the issue still happens.

**Comment by alqa-dash** [comment] 2017-03-07 05:47
Unfortunately this commit doesn't do the job in my case. I figured out that after the call has been started something changed its state to hold (fires provider:(CXProvider *)provider performSetHeldCallAction:) and I cannot mend it yet.

**Comment by alqa-dash** [comment] 2017-03-07 07:46
Update: I've discovered that there is second call while the first one is in progress and not answered yet. Below is the excerpt from debug log:
10 ) CallKit : Starting Call
2017-03-07 10:40:07.589299 linphone[6933:1341045] [Debug] ios/(roviderDelegate.m:206 ) CallKit : Audio session activated
2017-03-07 10:40:07.772685 linphone[6933:1341045] [Debug] ios/(roviderDelegate.m:110 ) CallKit : Starting Call
2017-03-07 10:40:07.799692 linphone[6933:1341045] [Debug] ios/(roviderDelegate.m:151 ) CallKit : Call paused status changed
2017-03-07 10:40:07.829303 linphone[6933:1341045] [Debug] ios/(roviderDelegate.m:224 ) CallKit : Call changed
2017-03-07 10:40:07.952883 linphone[6933:1341045] [Debug] ios/(roviderDelegate.m:224 ) CallKit : Call changed
2017-03-07 10:40:08.206160 linphone[6933:1341045] [Debug] ios/(roviderDelegate.m:224 ) CallKit : Call changed
341045] [Debug] ios/(roviderDelegate.m:224 ) CallKit : Call changed
2017-03-07 10:40:13.873020 linphone[6933:1341045] [Debug] ios/(roviderDelegate.m:210 ) CallKit : Audio session deactivated

So the question is: is it possible to avoid second call initiation in Linphone v.3.10.2-549 or should I move to modern version?

**Comment by ReisBenjamin** [comment] 2017-03-07 08:34
it depends on what causes the second call... I've never encountered it so it may not be fixed yet.
I suggest you test on our last release 3.16.2 and if the issue still happens then we'l try to find where the second call is created and why.

**Comment by ReisBenjamin** [comment] 2017-03-07 10:06
Just to be sure do you use linphone-iphone or just liblinphone ?

**Comment by alqa-dash** [comment] 2017-03-07 10:10
I use Linphone-iphone.

**Comment by ReisBenjamin** [comment] 2017-03-07 10:13
Okay then please try our latest commit and tell me if the issue still happens.
I'm unable to reproduce it so maybe it has already been solved.

**Comment by alqa-dash** [comment] 2017-03-07 12:59
I checked it on 3.10.5 (git version) of Linphone-iPhone and there is no double call. But If is impossible to fix problem on 3.10.2, I will have to move all my modifications to new version...

**Comment by ReisBenjamin** [comment] 2017-03-07 13:04
Hello,

To what correspond your git version ? because current version of Linphone is 3.16.2 not 3.10.5...
If you don't want to move your modification you can cherry-pick all commits of CallKit between your version and the one that does not have the problem

**Comment by alqa-dash** [comment] 2017-03-07 13:17
I downloaded 3.10.5 a while ago and just keep it just in the case. Ok, I'm going to take a look at changelog of 3.16 soon. "Cherry-pick" is not an option in my case because I put that 3.10.2 in our local git repo having removed all original .git references.

**Closed** 2017-03-23 09:21 UTC
