### ISSUE TITLE
voice memo crash due to likely race condition fetching the .mkv file

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/linphone-iphone#942] opened 2024-07-05 17:13 UTC
Hi guys,

Using the App Store version of Linphone I noticed that oftentimes the app crashes when receiving an incoming voice recording.
I am able to reproduce it consistently and I believe it is due to a race condition where linphone tries to play the .mkv file before it is actually fetched from the server and decrypted.

To reproduce just send a voice memo to another user on iOS and have them open the recording from the incoming push notification. I believe there should be some type of delay or check that the .mkv has actually been downloaded and decrypted before Linphone tries to play it.

```
024-07-05 17:11:55:794 [linphone/liblinphone] MESSAGE [Ios App] didEnterForeground
2024-07-05 17:11:55:795 [linphone/ios] DEBUG (honeAppDelegate.m:613 ) UN : response received
2024-07-05 17:11:55:795 [linphone/ios] DEBUG (honeAppDelegate.m:614 ) <UNNotificationResponse: 0x300db17a0; actionIdentifier: com.apple.UNNotificationDefaultActionIdentifier, notification: <UNNotification: 0x300db00f0; source: org.linphone.phone date: 2024-07-05 16:11:49 +0000, request: <UNNotificationRequest: 0x300db04e0; identifier: B08B5945-C700-4C4E-970C-707B1C3C59D3, content: <UNNotificationContent: 0x102e0ff10; title: <redacted>, subtitle: <redacted>, body: <redacted>, summaryArgument: (null), summaryArgumentCount: 0, categoryIdentifier: msg_cat, launchImageName: , threadIdentifier: , attachments: (
), badge: 1, sound: <UNNotificationSound: 0x3028b9340>, realert: 0, interruptionLevel: 1, relevanceScore: 0.00, filterCriteria: (null), screenCaptureProhibited: 0, speechLanguage: (null), trigger: <UNPushNotificationTrigger: 0x3001adec0; contentAvailable: NO, mutableContent: YES>>, intents: (
)>>
2024-07-05 17:11:55:795 [linphone/ios] MESSAGE [Voice Message] Stopping shared player path = <nil>|⭕️
2024-07-05 17:11:55:797 [linphone/ios] MESSAGE (  PhoneMainView.m:645 ) Change current view to linphoneapp.ChatConversationViewSwift
2024-07-05 17:11:55:797 [linphone/liblinphone] ERROR Handler not found in RemoteConferenceListEventHandler.
2024-07-05 17:11:55:814 [linphone/mediastreamer] ERROR Could not get duration. No file is open
2024-07-05 17:11:55:833 [linphone/mediastreamer] ERROR Could not get duration. No file is open
2024-07-05 17:11:55:840 [linphone/mediastreamer] MESSAGE Opening /private/var/mobile/Containers/Shared/AppGroup/502F365D-F8DA-47A9-AD96-25AE602F2429/Library/Images//voice-recording-80586055-9BBF-42C6-A7A8-6B289F523850.mkv
2024-07-05 17:11:55:840 [linphone/mediastreamer] MESSAGE MKVPlayer: opening /private/var/mobile/Containers/Shared/AppGroup/502F365D-F8DA-47A9-AD96-25AE602F2429/Library/Images//voice-recording-80586055-9BBF-42C6-A7A8-6B289F523850.mkv
2024-07-05 17:11:55:840 [linphone/mediastreamer] WARNING MKVPlayer: no default video track. Looking for first video track
2024-07-05 17:11:55:840 [linphone/mediastreamer] WARNING MKVPlayer: no video track found
2024-07-05 17:11:55:841 [linphone/mediastreamer] MESSAGE MSMediaPlayer: closing file.
2024-07-05 17:11:55:841 [linphone/mediastreamer] MESSAGE MKVPlayer: closed.
```

Are you guys already aware of this bug? I would assume so since the version in the App Store is 5.2.2 from December 2023 and the crash happens consistently.

Cheers,
Peter

**Comment by harut420** [comment] 2024-07-07 10:46
Hello Peter,
same here....

**Comment by petervnv** [comment] 2024-07-09 18:31
Hi @harut420 

I'm pretty certain this bug affects everyone but there doesn't seem to be a fix in sight. The latest commit in this repo is from 5 months ago... Not much action or bug fixes here.

Meanwhile I have at least figured out a "dirty hack" that doesn't solve the underlying issue but at least prevents the app from crashing when trying to play a voice memo.

In Classes/Swift/Util/AudioPlayer.swift I added an if statement to prevent the crash if the mkv file isn't available.

In lines 59-60 try adding this

```
if (path != nil){
                try linphonePlayer?.open(filename: path!)
                try linphonePlayer?.start()
            }
```

Hope this helps to at least prevent the annoying crashes.

Cheers,
Peter

**Comment by Viish** [comment] 2024-07-09 21:41
Hi @petervnv,

It's not really fair of you to say that knowing we are working hard on a new version of the app.

Yes, this issue won't be fixed in the current 5.2 release but that doesn't mean we don't take it into account. Benoit is aware of it and as he is working on the chat right now can do what it takes to prevent it from happening again in the 6.0 to come.

I'm glad you got a workaround for the time being. 
FYI, since the 5.2.0 release a year ago, from all our users and clients, you're the first one with @harut420 to come across this crash.

Cheers,

**Comment by Viish** [comment] 2024-07-10 17:38
> I remember you said some months ago you were working on a new release for June, but we are almost half-way through July and I have not seem any mention of it anywhere or any branches for 6.0 in your gitlab.

Yes we are a bit behind schedule, Android 6.0 public beta is scheduled for next week and iOS has been delayed to August, the time to make sure that all existing features work as expected in the new version.

Public repositories (gitlab and github) will be updated once the public beta published.

> Do you have a community forum like the jitsi open source guys have?

We do not have a forum but mailings lists (user & dev) and you can subscribe to our newsletter to be kept informed of our news.

> I know of at least 3 other people that have experienced the same crash

There may be many people having this issue, but if none of them reports it it doesn't help much...

**Comment by harut420** [comment] 2024-08-06 12:14
> Hi @Viish
> 
> Sorry you felt that I was being unfair. I was merely stating the obvious.
> 
> I remember you said some months ago you were working on a new release for June, but we are almost half-way through July and I have not seem any mention of it anywhere or any branches for 6.0 in your gitlab.
> 
> May I kindly suggest that you guys communicate better with the community and at least aknowledge the bugs that are reported here? Do you have a community forum like the jitsi open source guys have? You can see [here](https://community.jitsi.org/) that it is very vibrant and the community actively supports the project and helps each other all the time. Just an idea to alleviate some of your work and foster a true sense of community that is common in most open source projects and would help to improve communication.
> 
> Strange that you state @harut420 and I are the only ones to come across this crash. I know of at least 3 other people that have experienced the same crash when opening the voice recording from an incoming notification on their iPhones. Since they're using the app store version I would assume you get those crash reports in your backend.
> 
> Cheers, Peter

this means you guys are no testing or are blind because it is impossible that you are not aware of this bug.

**Comment by Viish** [comment] 2024-08-06 12:22
Hi @harut420,

No, we do test our software...

As this looks like a race condition it means this isn't reproductible, and it's likely on our networks we never see it because it's fast enough, but not on others.
We have a lot of users & a lot of clients and I can tell you this is the first time we hear about it, but don't worry now that this has been reported it will be fixed in the next release.

Cheers,

**Comment by harut420** [comment] 2024-08-06 12:47
@Viish 
on the looks like you did not check what @petervnv send here as log.
2024-07-05 17:11:55:814 [linphone/mediastreamer] ERROR Could not get duration. No file is open
2024-07-05 17:11:55:833 [linphone/mediastreamer] ERROR Could not get duration. No file is open

So the problems that in the header it cannnot get duration of the msg.

**Comment by Viish** [comment] 2024-08-06 12:49
> So the problems that in the header it cannnot get duration of the msg.

No, that's not the issue.

**Comment by harut420** [comment] 2024-08-06 18:24
@Viish 
I think you couldn't play because you tested with the app open. Kill the app, send an audio that will launch the app, and 100% of the time the audio is 0 long. The things that you wrote on your network is fast does not have any sense at all.... Lan is as fast there as it is here. LOL These kinds of apologies are not welcome. excuse.
Harut420

**Comment by Viish** [comment] 2024-08-06 18:32
@harut420 It turns out I'm the one that implemented the voice message feature in our SDK, and given that I worked on this project for 14 years now I guess I'm a bit more qualified than you to analyse the issue.

I'll appreciate it if you can stop posting such inappropriate and unconstructive comments.

**Comment by harut420** [comment] 2024-08-07 08:03
@Viish 
If you took it personally and think it's a personal attack, I want to make it clear that it is not.

Here is a video with your app, where as you can see, all the audio messages sent arrive with a size of 0.
https://github.com/user-attachments/assets/0e14c6ea-3834-471c-9757-c2d804bf4739

Don't worry, I won't write anymore because there's no point in reporting issues since you say everything works fine and only two users are experiencing this problem.

Harut420

**Comment by Viish** [comment] 2024-08-07 08:07
> there's no point in reporting issues since you say everything works fine

I never said that. I said it was the first time we were hearing about it and that we will fix it in the next release.

**Comment by petervnv** [comment] 2024-08-28 16:31
Hi @Viish 

Hope all is well.

I'm back from vacation and noticed you released the 6.0 beta of Android. Well done :)
I will start testing it next week and will report back any bugs.

August is almost over but I don't see any beta release for iOS yet nor any branches (publically available). Is it still on schedule to be released soon?

Regarding the voice memo bug, I can always reproduce it 100% of the time if the receiving iPhone has the app closed when it receives the push with the voice memo attachment. In that case it is always 0 length, but if the app is open then indeed it fetches the mkv and works as expected. I have tested this on slow networks and super fast 5G and the behavior is always the same so I don't think it's related to network speed or quality.

Hope this helps.

Cheers,
Peter

**Comment by Viish** [comment] 2024-08-28 19:03
Hi @petervnv,

Yes our iOS public beta is a bit behind schedule but we should be able to publish it in the coming weeks.
We haven't tried to fix the voice message issue on 5.2, it will be part of 6.0.

Best regards,

**Comment by petervnv** [comment] 2024-09-04 12:22
Hi @harut420 

I tried that already and the bug remains.
I guess our only option is to disable voice memos and wait until the new version eventually is released and hopefully fixes it.

Cheers

**Comment by petervnv** [comment] 2024-09-16 18:47
Hi again @Viish,

Hope all is well.

It's been 3 weeks since your last message and I still don't see any iOS 6 beta release anywhere nor any activity in your public repos.
Is it still on schedule to be released soon (by the end of September) or has it been delayed again?

Also, where can I find the github branch for Android 6 beta? Is it not public?

Cheers,
Peter

**Comment by harut420** [comment] 2024-09-16 19:16
Hi @petervnv 
did you tryed already with sdk 5.3.83 ?   i have tested don't downloading it immedially and with some more toast that let user click again on msg it is at leat acceptable, audio arrive  after user click on toast with custom message.

i saw new 5.3..83 and did not tested already, but tomrrow i should test it and let you know if some news come from new sdk.
Harut420

**Comment by harut420** [comment] 2024-09-17 07:29
hi @petervnv 5.3.83 does not fix that.
Harut420

**Comment by Viish** [comment] 2024-09-17 07:59
Hi @petervnv,

> Is it still on schedule to be released soon (by the end of September) or has it been delayed again?

Yes, we still target the end of september to publish the first iOS 6.0.0 beta.

> Also, where can I find the github branch for Android 6 beta? Is it not public?

All 6.0 Android code is on the master branch of linphone-android repository.

Cheers,

**Comment by elisa-linphone** [comment] 2024-09-17 11:30
Hi everyone,

I'm working with Viish at Belledonne Communications, the publisher of Linphone software. I'm jumping into this discussion with some good news:
Since we've delayed the release of our 6.0 app, we've decided to address this bug in the 5.2. iOS version. I will be available in the next minor version 5.2.X version via the App Store.

Thank you again for your patience.
We had to postpone version 6.0 to prioritize some customer projects, but it's definitely coming soon!
In version 6.0, the user interface has been completely redesigned and rewritten from scratch using our SDK, providing an even smoother and more user-friendly experience.

Best regards,
Elisa

**Comment by elisa-linphone** [comment] 2024-09-17 11:31
*It will be available (not I :) )

**Comment by harut420** [comment] 2024-09-18 13:03
Hi @elisa-linphone i saw 5.2.3

## [5.2.3] - 2024-17-09
### Fixed
- Crash when attempting to play audio memo with nil path (multi device sending situation for example)
- Crash playing recorded call
- Callkit ignoring incoming call if a registration failure occured earlier (incl. network connection problems)
- Displaying of <?xml in chat list when last chat message received is a voice memo  

 I tested it, and it works on a local physical iPhone device. The audio message always arrives from notifications with a length greater than 0, and the audio is audible. However, when it is pushed to TestFlight, it does not work. From notifications, the audio still arrives with a length of 0 persistently.

**Comment by petervnv** [comment] 2024-09-20 13:09
Thanks everyone for the updates!
I will test it over the weekend but I'm having trouble [compiling latest 5.3.85 now](https://github.com/BelledonneCommunications/linphone-sdk/issues/430)

Cheers

**Comment by harut420** [comment] 2024-09-22 16:06
Hello @elisa-linphone  I tried the last modification

- Fix audio memo downlowing when opened from the notification

 and can confirm that it works ;-) congratulations and thank you very much.

 There remains a very small usability issue regarding the playback of audio messages: whenever another message is received, whether from a notification or not, while the audio message is playing, the playback stops. 

This requires the user to press play again to resume listening. This happens with text messages, other audio messages, or any other attachments.

@petervnv what problem do you have for compile 5.3.85?   i had not problems compiling it with Ninja . 
let me me know. 
Thanks
Harut420

**Closed** 2024-11-07 08:58 UTC
