### ISSUE TITLE
iOS app sometimes doesn't receive VOIP notification (in background mode) from Flexisip

### ISSUE THREAD

**Issue by QuyNguyenVu** [BelledonneCommunications/linphone-iphone#164] opened 2017-01-02 08:26 UTC
Iam using Linphone lib on iOS and Flexisip on server to build my voip app (voice call).
Everthing working well.
When mobile app in background mode, iam using pushkit to receivce notification from Flexisip to wakeup mobile app and show incoming call screen. However, it unstable working. Sometime it receive notification (and wakeup app), but sometime doesn't.

Why ? This problem from iOS or Flexisip ?

**Comment by ruchiDYL** [comment] 2017-05-24 00:41
I am also facing same issue in my VOIP app, after doing lots of digging I found that when app wakes up from suspended state or comes in from background, during Linphone relaunch process DNS resolving takes almost 20 sec time and it gets time out from Kamilio “ ERROR: <core> [tcp_main.c:4338]: tcpconn_main_timeout(): connect 172.58.19.226:27717 failed (timeout) “ or sometime this DNS resolving process is done after 20 sec  time delay and we receive the inbound call pop up.


after more digging on network level, I found that the DNS connection request goes for DNS resolving  have some invalid header with SRV and AAA results  such as “_sip._tcp.sip-abc-xyz.com”. which is totally unacceptable format. so server does not response and in its request attempt, sometime this later it receives good format request as well which cause the delayed response, and if does not attempt with right format, it gets time out and lost of call.

probably its a bug of Linphone, as just now doing more google I found it was a bug in Linphone Desktop and recently got fixed in feb. "https://github.com/BelledonneCommunications/linphone-desktop/issues/13”. I am stilling digging into this and probably will soon resolve this.

**Comment by ruchiDYL** [comment] 2017-05-24 00:46
@BelledonneComm  please have a look in this issue. due to this same behavior I am facing delay in registration also. please see attached file with packet captured.
Please let me know if you need any other information from my end relevant to this issue. 
![screen shot 2017-05-23 at 3 21 06 pm](https://cloud.githubusercontent.com/assets/25807284/26382196/79afdf58-3fdf-11e7-9b7b-527aae3fad35.png)

Thanks

**Comment by eliburke** [comment] 2017-05-24 01:00
I don't know about the original poster's problem, but we have always had a bad time with the DNS SRV queries, including long registration delays. Try turning it off with linphone_core_enable_dns_srv() or "dns_srv_enabled=0" in the [net] section of linphonerc-factory.

**Comment by ruchiDYL** [comment] 2017-05-24 03:04
Thanks Eli for your response and suggestion with possible work around. 
Would love to know if anyone else also having issue like this ...

Regards
Ruchi Agrawal

**Comment by ruchiDYL** [comment] 2017-05-24 18:41
@eliburke  Thanks for your workaround suggestion, I tried that and it stoped sending DNS-SRV requests and making process faster than earlier but still there are some DNS type 0 unknown request packets found sent from app and waiting for response, so the app still takes longer then expected time in lunching the app and showing inbound call popup. here is the Screenshot attached with that type 0 packet structure .
@BelledonneComm 
![screen shot 2017-05-24 at 11 10 10 am](https://cloud.githubusercontent.com/assets/25807284/26419887/ebefc42a-4075-11e7-923d-ce36bfcc193f.png)

**Comment by ruchiDYL** [comment] 2017-05-25 23:31
After blocking DNS-SRV request packets there were 4-5 unknown type(0) DNS packets available , which causes delay of around 5 seconds in launching the app, be causing app waits for receiving response which never comes. 

I don’t know why these packets were coming, wasted whole day finding out the cause and getting rid from them. 
as one of my teammate suggested to try disabling IPV6 and checking these packets, I did a blind test and got success, now the app launching/linphone registration process is faster like blinking eyes. 
and no more unused DNS packets received this time. 
this is just a temprory solution as we need IPV6 enabled for our app. 
From @ReisBenjamin @BelledonneComm  I wanna know if this any known bug for IPV6 or any patch provided in recent release? 

please provide me any solution for this issue.

**Comment by ReisBenjamin** [comment] 2017-08-10 14:14
Try last build we made some fixes concerning IPV6

reopen if not fixed.
Thanks

**Closed by ReisBenjamin** 2017-08-10 14:14 UTC
