### ISSUE TITLE
Blank white screen on fresh install and run 3.15.1 

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#139] opened 2016-11-18 19:04 UTC
@BelledonneComm @ReisBenjamin  Please see why it is happening 

https://drive.google.com/open?id=0Bw4mP9qjWSb_M2FkUFpoVUItZFU

**Comment by JFSene** [comment] 2016-11-18 19:37
@TheEngineerz Is that a brand new build? Did you touch the code anywhere?
did you Enable ou disable any of the plugins?

**Comment by TheEngineerz** [comment] 2016-11-18 19:41
Not even a single touch . yes today i downloaded a brand new and build it.

**Comment by JFSene** [comment] 2016-11-18 19:46
Some minor changes have been commited in the last 24h, maybe something broke. Update your dir, or download it again. Make sure you're downloading from the master branch

**Comment by TheEngineerz** [comment] 2016-11-18 19:50
Yes i am downloading again using this command
git clone https://github.com/BelledonneCommunications/linphone-iphone.git

Hope it will work

**Comment by TheEngineerz** [comment] 2016-11-18 21:24
@JFSene @ReisBenjamin I have downloaded again each and every thing from scratch and build successfully but still i am seeing blank white screen. .My Xcode version is 8.0. Kindly have a look on code and I think Main storyboard is broken . when i click on the main storyboard i see something like attached picture.
![screen shot 2016-11-19 at 2 21 52 am](https://cloud.githubusercontent.com/assets/5149947/20447149/3392578e-adff-11e6-8fdf-a08ff9d6a941.png)

**Comment by TheEngineerz** [comment] 2016-11-19 22:07
@JFSene @ReisBenjamin anybody can look into this issue ? Please commit the unbroken version of storyboard that works.

**Comment by TheEngineerz** [comment] 2016-11-20 10:33
This is 3d view
![screen shot 2016-11-20 at 3 32 54 pm](https://cloud.githubusercontent.com/assets/5149947/20462154/b73fb904-af36-11e6-9f27-0f4eec0c7acf.png)

**Comment by ReisBenjamin** [comment] 2016-11-21 09:30
Hi @TheEngineerz,

I can't reproduce your issue. Could you provide me with your app logs so that I can see if something's wrong.

Thank you

**Comment by dinnysingh** [comment] 2016-11-21 09:44
We are facing the same issue of blank white screen. The assistant screen has this white view. We downloaded master 3 days back and today as well. Same issue. Please advise

**Comment by ReisBenjamin** [comment] 2016-11-21 14:56
Hi,

The issue has been fixed in commit bc144e218be5656981f087ffcdf37bb022fc3145
Could you confirm it doesn't reproduce with you too ?

Thanks

**Comment by dinnysingh** [comment] 2016-11-22 08:07
Hi @ReisBenjamin, It is working fine now 👍 

Thanks for the fix. Cheers

**Closed** 2016-12-08 11:31 UTC
