### ISSUE TITLE
SIP Registration , IO Error issue

### ISSUE THREAD

**Issue by kannanprasad87** [BelledonneCommunications/linphone-iphone#44] opened 2016-02-25 16:00 UTC
Hi All,
When I am trying with the latest code in Master branch,I am getting io error while connecting to the server. Please confirm is this a know issue? But code is working proper in simulator.

Please find the attached screen shots for the correct error and the build versions.
![img_20160225_204103](https://cloud.githubusercontent.com/assets/888393/13325198/ddd452e0-dc06-11e5-84ce-862323b2701b.jpg)
![img_20160225_204323](https://cloud.githubusercontent.com/assets/888393/13325209/e9660856-dc06-11e5-8a3f-c2ceb62bf552.jpg)

Thanks 
Kannan P

**Comment by kannanprasad87** [comment] 2016-03-01 13:34
Any one facing the same issue ?

**Comment by bagage** [comment] 2016-03-01 13:38
Well, I thought a bit more about it and it looks like I can reproduce in an almost predicable way.  I am not sure it will solve your concerns, but I'll let you know when my relative issue is fixed.
Please share any mindful information if any!

**Comment by kannanprasad87** [comment] 2016-03-01 15:09
One thing I have noticed is that , this issue doesn't occur in simulator.

Is it belleSIP bug or objective C bug ?

Thanks & Regards
Kannan Prasad

**Comment by kannanprasad87** [comment] 2016-03-02 04:25
Hi All,

My project is stuck over here. As I have committed the client LinPhone as
the solution after seeing the code working fine in the simulator.
When I scheduled the demo and tried from the device the issue blocks me.
Please help me to get out of this .

Are you able to get the root cause of this issue ?
Do we have any ETA for this bug. If we have answer for these questions . I
can take a decision on this solution.

Thanks & Regards
Kannan


*Thanks & Regards*

*Kannan Prasad*

**Comment by bagage** [comment] 2016-03-02 09:08
No ETA yet, however if you need a faster fix you should contact [Belledonne Communications](http://www.belledonne-communications.com/) for a support contract.
This issue seems rather server specific, so it has not a high priority for us yet.

**Comment by eliburke** [comment] 2016-03-02 14:22
It could be unrelated, but I think there is confusion in the SAL code between SalReasonIOError and SalReasonServiceUnavailable. You can see this in
sal_reason_to_sip_code() -- both errors return 503
_sal_reason_from_sip_code() -- 0 returns IOError, 503 returns Service Unavailable 
subscribe_refresher_listener() -- detects 503, returns IOError

**Comment by bagage** [comment] 2016-03-07 10:34
@eliburke indeed I do not think there is a relation with it there; it's actually the expected behavior for subscriptions.

**Comment by kannanprasad87** [comment] 2016-03-07 12:25
What you mean by subscriptions ??can you please get me more info on this ...

New app store build also have the same bug, earlier it was not the case.
Thanks & Regards
Kannan Prasad

**Comment by bagage** [comment] 2016-03-07 12:31
@kannanprasad87 please give me a version name/number that works for you - it should speed up resolution considerably.

**Comment by kannanprasad87** [comment] 2016-03-07 14:55
Please see the related bug in the git hub, I have attached the screen shots
there.

Thanks & Regards
Kannan Prasad

**Comment by bagage** [comment] 2016-03-07 15:22
What is the related bug? I do not see any working version here?

**Comment by kannanprasad87** [comment] 2016-03-07 15:26
In the repository bug #44.

Thanks & Regards
Kannan Prasad

**Comment by bagage** [comment] 2016-03-07 15:40
Screenshots show an IO error message with registration failed, not something I would say is working. To make it clear:

Did you ever successfully registered on your iPhone using Linphone in the past, and if so, what was the exact version you were running?

**Comment by kannanprasad87** [comment] 2016-03-07 15:59
I am able to register with my linphone account, but throws this error with
my SIP server. I am using the code from master branch. As of now I am away
from my code base, so won't be able to get exact version number.

And one more thing to be noted with this is that, linphone Android works
fine .

Thanks & Regards
Kannan Prasad

**Comment by kannanprasad87** [comment] 2016-03-07 16:00
PFA for the version details.

Thanks & Regards
Kannan Prasad

**Comment by bagage** [comment] 2016-03-08 13:41
This is probably an issue with your server. I am closing this for now since it is working quite fine with almost every over servers in the universe. Please check with your server administrator. 

Cheers,

**Closed by bagage** 2016-03-08 13:41 UTC

**Comment by kannanprasad87** [comment] 2016-03-09 09:38
Some one already admitted this is a bug from linphone client code , they
why this sudden U turn. Feeling confused .

Thanks & Regards
Kannan Prasad

**Comment by NadeeshanJayawardana** [comment] 2016-07-29 12:34
Thats because your device might be using IPV6 network my friend. i'm facing to the same issue while I'm trying to configure linphone source to IPV6 network comfortable. little hint which i think might be help you. go to the linphone settings and try to enable IPV6 under network setting

Cheers,

**Comment by grandbudha** [comment] 2019-12-21 20:39
Try by adding 2 properties inside your ps_endpoints table-

rewrite_contact=yes
rtp_symmetric = yes.

If you are playing with files not with DB then do try to add these files under 
type=endpoint

I guess it might work for you and for others. Thank you.

**Comment by saenkoyd** [comment] 2020-03-25 05:02
Had the same issue.
Works fine if there is only one simulator on Mac.
If use 2 simulators or on the device - io error.

Cant understand where problem is...
Could someone give the answer?
Thank you!

**Comment by piyush-ebizz** [comment] 2020-10-22 05:17
> Have the same issue.
> Works fine if there is only one simulator on Mac.
> If use 2 simulators or on the device - io error.
> 
> Cant understand where problem is...
> Could someone give the answer?
> Thank you!

Have you found any solution for this?

**Comment by chan1600** [comment] 2021-01-07 03:16
I also face the same problem when I used the C# linphone SDK 4.3.5 in my app.
We have 9 iOS phones for testing, only 1 phone is facing the io error issue, even uninstall/reinstall the app.
I still don't have an idea to fix the issue.

While I also installed the Linphone App to test on that problematic phone (iphone X), the phone can work and register successfully with Linphone app. And, it can call and talk without an issue. So, the problem only happen with my app.  

I tested with                 
Core.Ipv6Enabled = true;
Core.Ipv6Enabled = false;
and keeps the iOS version up to date.
it makes no different. 

And 1 more thing is, I tried to upgrade the phone from iPhone X to iPhone 11 with all data transferred, then the iPhone 11 will also has the same problem. I checked the setting, I have provided Microphone permission for the app.

I also checked my server database, I don't see the problem yet.
Do you have any idea what the problem is?

**Comment by jiejianyou** [comment] 2021-02-20 10:13
me too

**Comment by jiejianyou** [comment] 2021-02-20 10:29
==  Set lc.ipv6Enabled = false, it's ok again

**Comment by saenkoyd** [comment] 2021-06-07 16:08
Probably, sip_random_port=1 will fix your problems
