### ISSUE TITLE
When saving contact and reloading address book has error for country code

### ISSUE THREAD

**Issue by Flipper1** [BelledonneCommunications/linphone-iphone#158] opened 2016-12-22 10:04 UTC
Hi,
I've implemented some code for saving multiple contacts, but when I save them, it has problem with my contacts from phone suddenly, it says "Unknown ccc for e164 like number" on "onPresenceChanged" notification. Country code is +46.

**Comment by ReisBenjamin** [comment] 2016-12-22 10:34
To which country this code corresponds ?

**Comment by Flipper1** [comment] 2016-12-22 10:36
Sweden, and now new one +43, that is Austria

**Comment by ReisBenjamin** [comment] 2016-12-22 10:40
You should use +1 46 for sweden I believe.
However for Austria +43 is correct...
Can you show me what your code looks like ?

**Comment by Flipper1** [comment] 2016-12-22 10:43
These are numbers from my phone book, I have not added them, I have added some SIP contacts, but the problem is, when I save and reload, this is already implemented notification responser in UIContactCell, sometimes it works, sometimes it does not: 

 (void)onPresenceChanged:(NSNotification *)k {
	LinphoneFriend *f = [[k.userInfo valueForKey:@"friend"] pointerValue];
	// only consider event if it's about us
	if (!_contact.friend || f != _contact.friend) { // at this line, it says above error
		return;
	}
	[self setContact:_contact];
}

**Comment by ReisBenjamin** [comment] 2016-12-22 10:48
I don't reproduce your issue...
I tried to add a fake number in +46 and +43 and saved the contact without issues both from the app and the Iphone contacts.
Did you change anything in the code ?

**Comment by Flipper1** [comment] 2016-12-22 10:49
No, I have not changed anything.

**Comment by ReisBenjamin** [comment] 2016-12-22 10:53
Is your linphone version up-to-date ?

**Comment by Flipper1** [comment] 2016-12-22 10:54
It is 3.15 with Linphone Core 3.10.2

**Comment by ReisBenjamin** [comment] 2016-12-22 10:57
Try to do a git pull and git submodule update --recursive --init to be up to date.
Since it works for me maybe it has been fixed in a more recent version.

**Comment by Flipper1** [comment] 2016-12-22 10:59
Ok, I'll try

**Comment by ReisBenjamin** [comment] 2017-08-10 14:10
NO update, please reopen if not fixed.

Thanks

**Closed by ReisBenjamin** 2017-08-10 14:10 UTC
