### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by amesty** [BelledonneCommunications/linphone-iphone#68] opened 2016-05-17 08:52 UTC
LinphoneManager.m

- (void)iterate {
	linphone_core_iterate(theLinphoneCore);
}

2016-05-17 16:47:46.024 linphone[2038:589918] W/ios/(  StatusBarView.m:141 ) Received new NOTIFY from voice mail but could not find 'voice-message' in BODY. Ignoring it.
2016-05-17 16:47:46.025 linphone[2038:589918] I/lib/Linphone core [0x126070c00] notifying [notify_received]
2016-05-17 16:47:46.025 linphone[2038:589918] I/lib/LinphoneEvent [0x128188fc0] moving to subscription state LinphoneSubscriptionTerminated
2016-05-17 16:47:46.025 linphone[2038:589918] E/bel/Object [0x128188fc0] freed twice or corrupted !
2016-05-17 16:47:46.026 linphone[2038:589918] E/bel/Object type might be [LinphoneEvent]
2016-05-17 16:47:46.026 linphone[2038:589918] F/bel/Fatal object error encountered, aborting.

**Comment by bagage** [comment] 2016-05-17 09:34
Duplicate of #60

**Closed by bagage** 2016-05-17 09:34 UTC
